In [1]:
from datetime import timedelta
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import (mean_squared_error,
                             r2_score, mean_absolute_error,
                             mean_absolute_percentage_error)
from numpy import sqrt

In [2]:
def error_by_horizon(df_pred, df_ref):
    """
    Calculate error metrics for each horizon in the prediction DataFrame.
    """
    horizons = df_pred.columns
    error_metrics = {}

    for horizon in horizons:
        mse = mean_squared_error(df_ref[horizon], df_pred[horizon])
        r2 = r2_score(df_ref[horizon], df_pred[horizon])
        mae = mean_absolute_error(df_ref[horizon], df_pred[horizon])
        mape = mean_absolute_percentage_error(df_ref[horizon], df_pred[horizon])
        rmse = sqrt(mse)

        error_metrics[horizon] = {
            'MSE': mse,
            'R2': r2,
            'MAE': mae,
            'MAPE': mape,
            'RMSE': rmse
        }

    return pd.DataFrame(error_metrics).T

def general_error(df_pred, df_ref):
    """
    Calculate general error metrics for the entire prediction DataFrame.
    """
    mse = mean_squared_error(df_ref, df_pred)
    r2 = r2_score(df_ref, df_pred)
    mae = mean_absolute_error(df_ref, df_pred)
    mape = mean_absolute_percentage_error(df_ref, df_pred)
    rmse = float(sqrt(mse))

    return {
        'MSE': mse,
        'R2': r2,
        'MAE': mae,
        'MAPE': mape,
        'RMSE': rmse
    }

def general_error_by_file(df_pred_path, df_ref_path):
    """
    Load prediction and reference DataFrames from CSV files and calculate general error metrics.
    """
    df_pred = pd.read_csv(df_pred_path, index_col=0, parse_dates=True)
    df_ref = pd.read_csv(df_ref_path, index_col=0, parse_dates=True)
    #df_pred.drop(columns=['extra'], inplace=True)

    return general_error(df_pred, df_ref)

def error_by_horizon_by_file(df_pred_path, df_ref_path):
    """
    Load prediction and reference DataFrames from CSV files and calculate error metrics.
    """
    df_pred = pd.read_csv(df_pred_path, index_col=0, parse_dates=True)
    df_ref = pd.read_csv(df_ref_path, index_col=0, parse_dates=True)
    #df_pred.drop(columns=['extra'], inplace=True)

    return error_by_horizon(df_pred, df_ref)

def traspose_series_from_df_row(df_pred, row):
    aux_df = df_pred.reset_index()
    transposed_values = aux_df.iloc[row,:].values
    #transposed_values.extend(aux_df.iloc[:,1].values)
    dates = [transposed_values[0] + timedelta(weeks=i) for i in range(len(transposed_values) -1)]
    transposed_series = pd.Series(transposed_values[1:], index=dates, name='val')
    return transposed_series

def plot_all_ref_pred(df_pred, df_ref):

    for i in range(8):
        traspose_series_pred = traspose_series_from_df_row(df_pred, i)
        traspose_series_ref = traspose_series_from_df_row(df_ref, i)

        #plot

        plt.figure(figsize=(10, 5))
        traspose_series_pred.plot(label='Prediction')
        traspose_series_ref.plot(label='Reference')
        plt.title('Prediction vs Reference')
        plt.xlabel('Date')
        plt.ylabel('Value')
        plt.legend()
        plt.grid()
        plt.show()

In [3]:
error_by_horizon_by_file("../../experiments/exp_2025-07-05/res_config1.json/pred.csv",
                         "../../experiments/exp_2025-07-05/res_config1.json/ref.csv")

        MSE        R2       MAE      MAPE      RMSE
1  0.105111  0.147879  0.279378  0.512308  0.324208
2  0.144625  0.058480  0.299311  0.449273  0.380296
3  0.092808  0.203714  0.257742  0.459652  0.304644
4  0.063012  0.249741  0.191989  0.389229  0.251023
5  0.064970  0.065707  0.228292  0.425929  0.254893
6  0.067978 -0.068048  0.220513  0.443322  0.260725
7  0.084069 -0.071263  0.261367  0.516555  0.289947
8  0.112940 -0.035397  0.301305  0.563353  0.336066

In [4]:
error_by_horizon_by_file("../../experiments/exp_2025-07-05/res_config2.json/pred.csv",
                         "../../experiments/exp_2025-07-05/res_config2.json/ref.csv")

        MSE        R2       MAE      MAPE      RMSE
1  0.006397  0.948140  0.048719  0.094157  0.079981
2  0.087511  0.430296  0.204880  0.281571  0.295822
3  0.090818  0.220785  0.230334  0.348000  0.301361
4  0.117906 -0.403850  0.255001  0.422513  0.343374
5  0.119841 -0.723355  0.248136  0.425252  0.346181
6  0.046461  0.270020  0.174456  0.346708  0.215547
7  0.055765  0.289405  0.197224  0.407725  0.236147
8  0.075092  0.311585  0.229518  0.439534  0.274029

In [5]:
error_by_horizon_by_file("../../experiments/exp_2025-07-05/res_config3.json/pred.csv",
                         "../../experiments/exp_2025-07-05/res_config3.json/ref.csv")

        MSE        R2       MAE      MAPE      RMSE
1  0.075913  0.384585  0.212127  0.315275  0.275522
2  0.136791  0.109477  0.256431  0.278130  0.369853
3  0.087279  0.251156  0.231388  0.306036  0.295429
4  0.058348  0.305283  0.187831  0.284646  0.241552
5  0.055582  0.200710  0.146933  0.205626  0.235759
6  0.061470  0.034197  0.198234  0.295352  0.247932
7  0.084365 -0.075036  0.237698  0.342953  0.290457
8  0.122008 -0.118525  0.260428  0.325861  0.349296

In [6]:
error_list = [
    general_error_by_file("../../experiments/exp_2025-07-05/res_config1.json/pred.csv",
                 "../../experiments/exp_2025-07-05/res_config1.json/ref.csv"),
    general_error_by_file("../../experiments/exp_2025-07-05/res_config2.json/pred.csv",
                         "../../experiments/exp_2025-07-05/res_config2.json/ref.csv"),
    general_error_by_file("../../experiments/exp_2025-07-05/res_config3.json/pred.csv",
                         "../../experiments/exp_2025-07-05/res_config3.json/ref.csv")
]

error_df = pd.DataFrame(error_list, index=['config1-prophet', 'config2-sarimax', 'config3-lstm'])
error_df

                      MSE        R2       MAE      MAPE      RMSE
config1-prophet  0.091939  0.068852  0.254987  0.469953  0.303215
config2-sarimax  0.074974  0.167878  0.198534  0.345682  0.273814
config3-lstm     0.085219  0.136481  0.216384  0.294235  0.291924

In [7]:
print(error_df)

                      MSE        R2       MAE      MAPE      RMSE
config1-prophet  0.091939  0.068852  0.254987  0.469953  0.303215
config2-sarimax  0.074974  0.167878  0.198534  0.345682  0.273814
config3-lstm     0.085219  0.136481  0.216384  0.294235  0.291924