In [55]:
from datetime import timedelta
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import (mean_squared_error,
                             r2_score, mean_absolute_error,
                             mean_absolute_percentage_error)
from numpy import sqrt

In [56]:
def error_by_horizon(df_pred, df_ref):
    """
    Calculate error metrics for each horizon in the prediction DataFrame.
    """
    horizons = df_pred.columns
    error_metrics = {}

    for horizon in horizons:
        mse = mean_squared_error(df_ref[horizon], df_pred[horizon])
        r2 = r2_score(df_ref[horizon], df_pred[horizon])
        mae = mean_absolute_error(df_ref[horizon], df_pred[horizon])
        mape = mean_absolute_percentage_error(df_ref[horizon], df_pred[horizon])
        rmse = sqrt(mse)

        error_metrics[horizon] = {
            'MSE': mse,
            'R2': r2,
            'MAE': mae,
            'MAPE': mape,
            'RMSE': rmse
        }

    return pd.DataFrame(error_metrics).T

def general_error(df_pred, df_ref):
    """
    Calculate general error metrics for the entire prediction DataFrame.
    """
    mse = mean_squared_error(df_ref, df_pred)
    r2 = r2_score(df_ref, df_pred)
    mae = mean_absolute_error(df_ref, df_pred)
    mape = mean_absolute_percentage_error(df_ref, df_pred)
    rmse = float(sqrt(mse))

    return {
        'MSE': mse,
        'R2': r2,
        'MAE': mae,
        'MAPE': mape,
        'RMSE': rmse
    }

def general_error_by_file(df_pred_path, df_ref_path):
    """
    Load prediction and reference DataFrames from CSV files and calculate general error metrics.
    """
    df_pred = pd.read_csv(df_pred_path, index_col=0, parse_dates=True)
    df_ref = pd.read_csv(df_ref_path, index_col=0, parse_dates=True)
    df_pred.drop(columns=['extra'], inplace=True)

    return general_error(df_pred, df_ref)

def error_by_horizon_by_file(df_pred_path, df_ref_path):
    """
    Load prediction and reference DataFrames from CSV files and calculate error metrics.
    """
    df_pred = pd.read_csv(df_pred_path, index_col=0, parse_dates=True)
    df_ref = pd.read_csv(df_ref_path, index_col=0, parse_dates=True)
    df_pred.drop(columns=['extra'], inplace=True)

    return error_by_horizon(df_pred, df_ref)

def traspose_series_from_df_row(df_pred, row):
    aux_df = df_pred.reset_index()
    transposed_values = aux_df.iloc[row,:].values
    #transposed_values.extend(aux_df.iloc[:,1].values)
    dates = [transposed_values[0] + timedelta(weeks=i) for i in range(len(transposed_values) -1)]
    transposed_series = pd.Series(transposed_values[1:], index=dates, name='val')
    return transposed_series

def plot_all_ref_pred(df_pred, df_ref):

    for i in range(8):
        traspose_series_pred = traspose_series_from_df_row(df_pred, i)
        traspose_series_ref = traspose_series_from_df_row(df_ref, i)

        #plot

        plt.figure(figsize=(10, 5))
        traspose_series_pred.plot(label='Prediction')
        traspose_series_ref.plot(label='Reference')
        plt.title('Prediction vs Reference')
        plt.xlabel('Date')
        plt.ylabel('Value')
        plt.legend()
        plt.grid()
        plt.show()

In [57]:
error_by_horizon_by_file("../../experiments/exp_2025-06-29/res_config1.json/pred_95.csv",
                         "../../experiments/exp_2025-06-29/res_config1.json/ref_95.csv")

        MSE        R2       MAE      MAPE      RMSE
1  0.105111  0.147879  0.279378  0.512308  0.324208
2  0.144625  0.058480  0.299311  0.449273  0.380296
3  0.092808  0.203714  0.257742  0.459652  0.304644
4  0.063012  0.249741  0.191989  0.389229  0.251023
5  0.064970  0.065707  0.228292  0.425929  0.254893
6  0.067978 -0.068048  0.220513  0.443322  0.260725
7  0.084069 -0.071263  0.261367  0.516555  0.289947
8  0.112940 -0.035397  0.301305  0.563353  0.336066

In [58]:
error_by_horizon_by_file("../../experiments/exp_2025-06-29/res_config2.json/pred_97.csv",
                         "../../experiments/exp_2025-06-29/res_config2.json/ref_97.csv")

        MSE        R2       MAE      MAPE      RMSE
1  0.013315  0.892054  0.101244  0.178163  0.115392
2  0.056226  0.633965  0.165025  0.209332  0.237120
3  0.028763  0.753214  0.137135  0.212650  0.169597
4  0.030943  0.631577  0.141492  0.234399  0.175906
5  0.032695  0.529838  0.148471  0.238987  0.180817
6  0.048355  0.240256  0.204646  0.362126  0.219898
7  0.080300 -0.023232  0.249799  0.426712  0.283373
8  0.102794  0.057618  0.289077  0.464848  0.320615

In [59]:
error_by_horizon_by_file("../../experiments/exp_2025-06-29/res_config3.json/pred_98.csv",
                         "../../experiments/exp_2025-06-29/res_config3.json/ref_98.csv")

        MSE        R2       MAE      MAPE      RMSE
1  0.081985  0.335358  0.234872  0.393066  0.286330
2  0.145465  0.053008  0.276088  0.358097  0.381399
3  0.090222  0.225905  0.241690  0.381188  0.300369
4  0.079060  0.058664  0.234327  0.404491  0.281177
5  0.070470 -0.013378  0.214212  0.385826  0.265461
6  0.062803  0.013258  0.198446  0.347212  0.250605
7  0.073548  0.062806  0.252273  0.464135  0.271197
8  0.108125  0.008748  0.294909  0.510397  0.328824

In [60]:
error_list = [
    general_error_by_file("../../experiments/exp_2025-06-29/res_config1.json/pred_95.csv",
                 "../../experiments/exp_2025-06-29/res_config1.json/ref_95.csv"),
    general_error_by_file("../../experiments/exp_2025-06-29/res_config2.json/pred_97.csv",
                         "../../experiments/exp_2025-06-29/res_config2.json/ref_97.csv"),
    general_error_by_file("../../experiments/exp_2025-06-29/res_config3.json/pred_98.csv",
                         "../../experiments/exp_2025-06-29/res_config3.json/ref_98.csv")
]

error_df = pd.DataFrame(error_list, index=['config1-prophet', 'config2-sarimax', 'config3-lstm'])
error_df

                      MSE        R2       MAE      MAPE      RMSE
config1-prophet  0.091939  0.068852  0.254987  0.469953  0.303215
config2-sarimax  0.049174  0.464411  0.179611  0.290902  0.221752
config3-lstm     0.088960  0.093046  0.243352  0.405552  0.298261

In [61]:
print(error_df)

                      MSE        R2       MAE      MAPE      RMSE
config1-prophet  0.091939  0.068852  0.254987  0.469953  0.303215
config2-sarimax  0.049174  0.464411  0.179611  0.290902  0.221752
config3-lstm     0.088960  0.093046  0.243352  0.405552  0.298261